/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.miragon.libs.taskmanager.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.miragon.libs.taskmanager.client.apis.CompleteTaskControllerApi
import io.miragon.libs.taskmanager.client.models.UserTaskDto

class CompleteTaskControllerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CompleteTaskControllerApi
        //val apiInstance = CompleteTaskControllerApi()

        // to test completeTask
        should("test completeTask") {
            // uncomment below to test completeTask
            //val userTaskDto : UserTaskDto =  // UserTaskDto | 
            //apiInstance.completeTask(userTaskDto)
        }

    }
}
