/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.miragon.libs.taskmanager.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.miragon.libs.taskmanager.client.apis.LoadUserTaskControllerApi
import io.miragon.libs.taskmanager.client.models.UserTaskDto

class LoadUserTaskControllerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LoadUserTaskControllerApi
        //val apiInstance = LoadUserTaskControllerApi()

        // to test loadTasks
        should("test loadTasks") {
            // uncomment below to test loadTasks
            //val result : kotlin.collections.List<UserTaskDto> = apiInstance.loadTasks()
            //result shouldBe ("TODO")
        }

    }
}
