/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.miragon.libs.taskmanager.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.miragon.libs.taskmanager.client.apis.LoadMetadataControllerApi
import io.miragon.libs.taskmanager.client.models.MetadataDto

class LoadMetadataControllerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LoadMetadataControllerApi
        //val apiInstance = LoadMetadataControllerApi()

        // to test loadMetadata
        should("test loadMetadata") {
            // uncomment below to test loadMetadata
            //val result : MetadataDto = apiInstance.loadMetadata()
            //result shouldBe ("TODO")
        }

    }
}
