/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.miragon.libs.taskmanager.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.miragon.libs.taskmanager.client.apis.UserTaskControllerApi
import io.miragon.libs.taskmanager.client.models.JobRecordDto

class UserTaskControllerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserTaskControllerApi
        //val apiInstance = UserTaskControllerApi()

        // to test saveTask
        should("test saveTask") {
            // uncomment below to test saveTask
            //val jobRecordDto : JobRecordDto =  // JobRecordDto | 
            //val result : kotlin.String = apiInstance.saveTask(jobRecordDto)
            //result shouldBe ("TODO")
        }

        // to test updateTask
        should("test updateTask") {
            // uncomment below to test updateTask
            //val jobRecordDto : JobRecordDto =  // JobRecordDto | 
            //val result : kotlin.String = apiInstance.updateTask(jobRecordDto)
            //result shouldBe ("TODO")
        }

    }
}
