# Camunda Platform 7
camunda.bpm:
  client:
    base-url: ${CAMUNDA_BASE_URL:http://localhost:8081/engine-rest}
  disable-backoff-strategy: true

miranum:
  c7:
    auth.server.url: http://keycloak:9090/auth/realms/miranum/protocol/openid-connect/token
    client:
      id: miranum-worker
      secret: s3creT

