/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.miragon.libs.taskmanager.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.miragon.libs.taskmanager.client.models.CompleteTaskCommand

class CompleteTaskCommandTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CompleteTaskCommand
        //val modelInstance = CompleteTaskCommand()

        // to test the property `taskId`
        should("test taskId") {
            // uncomment below to test the property
            //modelInstance.taskId shouldBe ("TODO")
        }

        // to test the property `variables`
        should("test variables") {
            // uncomment below to test the property
            //modelInstance.variables shouldBe ("TODO")
        }

    }
}
