/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.miragon.libs.taskmanager.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.miragon.libs.taskmanager.client.models.MetadataDto
import io.miragon.libs.taskmanager.client.models.ProcessApplication

class MetadataDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MetadataDto
        //val modelInstance = MetadataDto()

        // to test the property `processApplications`
        should("test processApplications") {
            // uncomment below to test the property
            //modelInstance.processApplications shouldBe ("TODO")
        }

    }
}
