/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.miragon.libs.taskmanager.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.miragon.libs.taskmanager.client.models.ProcessApplication

class ProcessApplicationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProcessApplication
        //val modelInstance = ProcessApplication()

        // to test the property `processId`
        should("test processId") {
            // uncomment below to test the property
            //modelInstance.processId shouldBe ("TODO")
        }

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `startable`
        should("test startable") {
            // uncomment below to test the property
            //modelInstance.startable shouldBe ("TODO")
        }

        // to test the property `startProcessUrl`
        should("test startProcessUrl") {
            // uncomment below to test the property
            //modelInstance.startProcessUrl shouldBe ("TODO")
        }

        // to test the property `startProcessFormUrl`
        should("test startProcessFormUrl") {
            // uncomment below to test the property
            //modelInstance.startProcessFormUrl shouldBe ("TODO")
        }

        // to test the property `loadTaskUrl`
        should("test loadTaskUrl") {
            // uncomment below to test the property
            //modelInstance.loadTaskUrl shouldBe ("TODO")
        }

        // to test the property `completeTaskUrl`
        should("test completeTaskUrl") {
            // uncomment below to test the property
            //modelInstance.completeTaskUrl shouldBe ("TODO")
        }

        // to test the property `updateTaskUrl`
        should("test updateTaskUrl") {
            // uncomment below to test the property
            //modelInstance.updateTaskUrl shouldBe ("TODO")
        }

    }
}
