/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.miragon.libs.taskmanager.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.miragon.libs.taskmanager.client.models.UserTaskDto

class UserTaskDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserTaskDto
        //val modelInstance = UserTaskDto()

        // to test the property `key`
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `elementId`
        should("test elementId") {
            // uncomment below to test the property
            //modelInstance.elementId shouldBe ("TODO")
        }

        // to test the property `processInstanceKey`
        should("test processInstanceKey") {
            // uncomment below to test the property
            //modelInstance.processInstanceKey shouldBe ("TODO")
        }

        // to test the property `bpmnProcessId`
        should("test bpmnProcessId") {
            // uncomment below to test the property
            //modelInstance.bpmnProcessId shouldBe ("TODO")
        }

        // to test the property `processDefinitionKey`
        should("test processDefinitionKey") {
            // uncomment below to test the property
            //modelInstance.processDefinitionKey shouldBe ("TODO")
        }

        // to test the property `variables`
        should("test variables") {
            // uncomment below to test the property
            //modelInstance.variables shouldBe ("TODO")
        }

        // to test the property `taskState`
        should("test taskState") {
            // uncomment below to test the property
            //modelInstance.taskState shouldBe ("TODO")
        }

        // to test the property `assignee`
        should("test assignee") {
            // uncomment below to test the property
            //modelInstance.assignee shouldBe ("TODO")
        }

    }
}
