server:
  port: 8883
application:
  rest:
    kitchen: "localhost:8881"
    payment: "localhost:8882"
zeebe:
  client:
    broker:
      gateway-address: "localhost:26500"
    security:
      plaintext: true

