/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.miragon.libs.taskmanager.client.apis

import com.fasterxml.jackson.annotation.JsonProperty

import org.springframework.web.client.RestClient
import org.springframework.web.client.RestClientResponseException

import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
import org.springframework.http.ResponseEntity
import org.springframework.http.MediaType


import io.miragon.libs.taskmanager.client.models.JobRecordDto
import io.miragon.libs.taskmanager.client.infrastructure.*

class UserTaskControllerApi(client: RestClient) : ApiClient(client) {

    constructor(baseUrl: String) : this(RestClient.builder()
        .baseUrl(baseUrl)
        .messageConverters { it.add(MappingJackson2HttpMessageConverter()) }
        .build()
    )


    @Throws(RestClientResponseException::class)
    fun saveTask(jobRecordDto: JobRecordDto): kotlin.String {
        val result = saveTaskWithHttpInfo(jobRecordDto = jobRecordDto)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun saveTaskWithHttpInfo(jobRecordDto: JobRecordDto): ResponseEntity<kotlin.String> {
        val localVariableConfig = saveTaskRequestConfig(jobRecordDto = jobRecordDto)
        return request<JobRecordDto, kotlin.String>(
            localVariableConfig
        )
    }

    fun saveTaskRequestConfig(jobRecordDto: JobRecordDto) : RequestConfig<JobRecordDto> {
        val localVariableBody = jobRecordDto
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "*/*"

        val params = mutableMapOf<String, Any>(
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/rest/task/save",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun updateTask(jobRecordDto: JobRecordDto): kotlin.String {
        val result = updateTaskWithHttpInfo(jobRecordDto = jobRecordDto)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun updateTaskWithHttpInfo(jobRecordDto: JobRecordDto): ResponseEntity<kotlin.String> {
        val localVariableConfig = updateTaskRequestConfig(jobRecordDto = jobRecordDto)
        return request<JobRecordDto, kotlin.String>(
            localVariableConfig
        )
    }

    fun updateTaskRequestConfig(jobRecordDto: JobRecordDto) : RequestConfig<JobRecordDto> {
        val localVariableBody = jobRecordDto
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "*/*"

        val params = mutableMapOf<String, Any>(
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/rest/task/update",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

}
