# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/
# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/configuration/

server:
  port: 9100

zeebe.client:
  cloud:
    region: ont-1
    clusterId: 2f2efc37-6219-4e69-b79b-edb662f2bc60
    clientId: rnBk9bqCERl.H86~q4jO7dtLRI8ETQLu
    clientSecret: J5A__vhVQfdJsQqwR~216sS3KHrgBPU-UQ_rFhxvC2o2WG75OKLT1AoV4NASIpao
