/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.miragon.libs.taskmanager.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param taskId 
 * @param variables 
 */


data class CompleteTaskCommand (

    @field:JsonProperty("taskId")
    val taskId: kotlin.Long,

    @field:JsonProperty("variables")
    val variables: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

