/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.miragon.libs.taskmanager.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param key 
 * @param intent 
 * @param elementId 
 * @param processInstanceKey 
 * @param bpmnProcessId 
 * @param processDefinitionKey 
 * @param variables 
 */


data class JobRecordDto (

    @field:JsonProperty("key")
    val key: kotlin.Long,

    @field:JsonProperty("intent")
    val intent: kotlin.String,

    @field:JsonProperty("elementId")
    val elementId: kotlin.String,

    @field:JsonProperty("processInstanceKey")
    val processInstanceKey: kotlin.Long,

    @field:JsonProperty("bpmnProcessId")
    val bpmnProcessId: kotlin.String,

    @field:JsonProperty("processDefinitionKey")
    val processDefinitionKey: kotlin.Long,

    @field:JsonProperty("variables")
    val variables: kotlin.collections.Map<kotlin.String, kotlin.Any>

)

