/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.miragon.libs.taskmanager.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param processId 
 * @param label 
 * @param startable 
 * @param startProcessUrl 
 * @param startProcessFormUrl 
 * @param loadTaskUrl 
 * @param completeTaskUrl 
 * @param updateTaskUrl 
 */


data class ProcessApplication (

    @field:JsonProperty("processId")
    val processId: kotlin.String,

    @field:JsonProperty("label")
    val label: kotlin.String,

    @field:JsonProperty("startable")
    val startable: kotlin.Boolean,

    @field:JsonProperty("startProcessUrl")
    val startProcessUrl: kotlin.String,

    @field:JsonProperty("startProcessFormUrl")
    val startProcessFormUrl: kotlin.String,

    @field:JsonProperty("loadTaskUrl")
    val loadTaskUrl: kotlin.String,

    @field:JsonProperty("completeTaskUrl")
    val completeTaskUrl: kotlin.String,

    @field:JsonProperty("updateTaskUrl")
    val updateTaskUrl: kotlin.String

)

